### ISSUE TITLE
'HierImageList' dataset is necessary for reproduce?

### ISSUE THREAD

**Issue by halbielee** [lwzeng/GC-Net#2]
Thank you for sharing your excellent job.

I have a question for your code. 

https://github.com/lwzeng/GC-Net/blob/b3ee0c0d8ff2e0bd65994c2a733dd884c8802ad5/classifier/classifier_vgg.py#L8

There is a undefined function in the provided code and using that ImageList is default.
_ImageList_ from _img_loader_hierarchy_ is necessary for reproducing the code?

Thanks!

**Comment by lwzeng** [comment]
This is not necessary. "Classification with Category Hierarchy" is a try in our research refer to the paper, "DANet: Divergent Activation for Weakly Supervised Object Localization". But in the end, we did not use this method.

**Comment by halbielee** [comment]
Thanks for the reply!
